### ISSUE TITLE
dominoes: Don't call the "invalid input" test invalid input?

### ISSUE THREAD

**Issue by petertseng** [exercism/xrust#100]
Concerning https://github.com/exercism/xrust/blob/master/exercises/dominoes/tests/dominoes.rs#L113

It's valid input for the function (it's a list of dominoes), it's just that it can't be chained. I would think we wouldn't want to call it `invalid_input`.

I'm just thinking about this as I figure out what to call it in the common JSON file

**Comment by IanWhitney** [comment]
`unchainable`? `no_chains`?

**Comment by petertseng** [comment]
I'll take it, `no_chains` it is. I also considered `cant_be_chained`. I am not too picky either way, I just had to pick something.
