### ISSUE TITLE
Add test case to Hamming that shows the difference between `len()` and `chars().count()`

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xrust#128]
I see this solution a lot

```rust
let x = "Hi";
let y = "Yo";

if x.len() == y.len() {
//do something
} else {
//do something else
}
```

But that's tricky in Rust because all strings are UTF-8 and the number of characters != the length of the string slice.

An example: https://play.rust-lang.org/?gist=b0fb8157fd7903333d9441164e0fffaf&version=stable&backtrace=0

I just saw this pop up in Hamming, so maybe exposing this difference via a test in that problem is a good idea.

**Comment by kytrinyx** [comment]
In the case of hamming for DNA mutations the UTF-8 issue doesn't really come into play. Do we have any other exercises where we could expose this?

**Comment by IanWhitney** [comment]
In our current problem set? Not really. Anagrams can do it, but that's going to move much later in the sequence. Maybe in a problem we haven't implemented yet?

**Comment by kytrinyx** [comment]
Yeah, maybe, though there's nothing obvious in the list: http://exercism.io/languages/rust/contribute

Maybe we need a new exercise that focuses on this explicitly. Go has the same thing.

**Comment by petertseng** [comment]
Since #175 now deals with the difference between bytes and characters, I think the original intent behind this is in fact covered, even if the test was added to a different exercise than Hamming. What say you?

**Comment by IanWhitney** [comment]
Sounds good.
