### ISSUE TITLE
test cases for nucleotide count should include handing of invalid sequences

### ISSUE THREAD

**Issue by lcowell** [exercism/xrust#149]
In some implementations I've seen of this exercise, if I were to pass in a sequence of ATCGLL, we see include `L: 2` in the results. There is no test to indicate if that behaviour is invalid and it doesn't seem right. Are we in favour of adding a test case to address invalid input or does that feel like it's outside the scope of this exercise?

**Comment by IanWhitney** [comment]
I have noticed the same. 

Currently there is not a standard, cross-track test suite for Nucleotide Count. It would probably be good to  create one, so that all tracks could handle this edge case.

**Comment by IanWhitney** [comment]
(Oh, also, thanks for adding the issue! Much appreciated)

**Comment by petertseng** [comment]
List of tracks that implement this exercise is at http://x.exercism.io/problems/nucleotide-count. I have not checked all of them but I know that at least [Haskell expects that invalid nucleotides result in an error](https://github.com/exercism/xhaskell/blob/master/exercises/nucleotide-count/nucleotide-count_test.hs) ), would be interesting to see how many other tracks expect the same

**Comment by petertseng** [comment]
Info on what other tracks are doing:

xgo now tests for sequences containing invalid nucleotides and expects that the function under test signals an error for them, as of https://github.com/exercism/xgo/pull/413
