### ISSUE TITLE
Exercise `Pangram` should define which alphabet is expected

### ISSUE THREAD

**Issue by cjschneider2** [exercism/xrust#150]
While doing this exercise I've noticed that the README.md does not mention which alphabet one should be checking against. I originally assumed an English alphabet, yet the last test in German being considered a pangram made me reconsider. I guess in summary the alphabet / language to be tested against should be defined exercise problem description, otherwise this is a rather unbounded problem.

**Comment by cjschneider2** [comment]
I can put up a pull request that fixes it, I just wanted other people's opinion on the matter.

**Comment by IanWhitney** [comment]
Clarification of the readme would certainly be useful. In the case of this exercise it's only looking for [ascii characters](http://ascii-code.com). Nothing in extended ascii (or unicode, etc.) should count.

The edge case that the German test is trying to cover is that non-ascii characters don't blow up your code. It does contain a full ascii pangram once you filter out all of the extended characters.

**Comment by kotp** [comment]
exercism/x-common#284 hopefully clarifies this.
