### ISSUE TITLE
Modifying all exercises to work with cargo

### ISSUE THREAD

**Issue by EduardoBautista** [exercism/xrust#18]
It looks like cargo will be the preferred way to run tests going forward.  Since it comes with Rust, we should probably set up the exercises so that `cargo run` and `cargo test` can be used.  I can help by making the changes.

**Comment by bitborn** [comment]
I'd really like to give this a bump.
Cargo has become the defacto way to do [testing in Rust](http://doc.rust-lang.org/book/testing.html) and [now ships with Rust](http://doc.crates.io/).

I'd be willing to create a pull request to add cargo to the exercises, if that's the direction we want to move.

**Comment by steveklabnik** [comment]
In general, they're gonna need updated period. But yes, Cargo should be involved.

**Comment by mirosval** [comment]
I'm new to Rust and was hoping to start learning using Exercism, but with Rust 1.0.0-beta I don't even know how to run the tests w/o cargo, because the docs just don't mention it.

So +1 for Cargo-based test for Rust Exercism!

**Comment by steveklabnik** [comment]
With beta out, it would be a decent time to start doing this.
