### ISSUE TITLE
Implement All Your Base

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xrust#181]
The problem is described in [its readme](https://github.com/exercism/x-common/blob/master/all-your-base.md)

- [ ] Use the [standard test definition](https://github.com/exercism/x-common/blob/master/all-your-base.json) as the basis for test/all-your-base.rs file
- [ ] Create an `example.rs` solution
- [ ] Place the problem in `config.json`
- [ ] Place the problem and describe its topics in `problems.md`

**Comment by petertseng** [comment]
For this and all other non-acronym: First item needs to change from test/acronym.rs to proper slug.

(Link is already correct)

**Comment by petertseng** [comment]
is in progres, #170

**Comment by IanWhitney** [comment]
This is why I need to programmatically create these issues & not copy & paste.

**Comment by petertseng** [comment]
Merged https://github.com/exercism/xrust/pull/170 as https://github.com/exercism/xrust/commit/9c527e465fd95eef5b4243f123acec76892f212f
