### ISSUE TITLE
Implement Alphametics

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xrust#182]
The problem is described in [its readme](https://github.com/exercism/x-common/blob/master/exercises/alphametics/description.md)
- [ ] Use the [standard test definition](https://github.com/exercism/x-common/blob/master/exercises/alphametics/canonical-data.json) as the basis for test/alphametics.rs file
- [ ] Create an `example.rs` solution
- [ ] Place the problem in `config.json`
- [ ] Place the problem and describe its topics in `problems.md`

**Comment by ijanos** [comment]
Hi there! Just a heads up, I'm working on this and you can expect a pull request soon.

**Comment by IanWhitney** [comment]
Awesome! Thanks, @ijanos
