### ISSUE TITLE
Implement Atbash Cipher

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xrust#183]
The problem is described in [its readme](https://github.com/exercism/x-common/blob/master/atbash-cihper.md)

- [ ] Use the [standard test definition](https://github.com/exercism/x-common/blob/master/exercises/atbash-cipher/canonical-data.json) as the basis for test/atabash-cipher.rs file
- [ ] Create an `example.rs` solution
- [ ] Place the problem in `config.json`
- [ ] Place the problem and describe its topics in `problems.md`

**Comment by cynicaldevil** [comment]
I can take up this issue! I have recently begun contributing to the Rust project and this issue will let me gain some more coding experience in rust! 

Note: the readme link is not working.

**Comment by petertseng** [comment]
Thanks! We would be happy to have you do this. Sorry about the README - the correct link should be https://github.com/exercism/x-common/blob/master/exercises/atbash-cipher/description.md

(I have corrected the README links at other issues of this kind as well)

**Comment by IanWhitney** [comment]
Looking forward to it. Thanks!

**Comment by cynicaldevil** [comment]
I have completed most of the work, but I noticed that only the first test in other crates are run, and the subsequent ones are ignored. Why so?

**Comment by IanWhitney** [comment]
Can you push up your code and make a PR? Then we can take a look.

**Comment by cynicaldevil** [comment]
Just to remind you, I have opened a PR [here](https://github.com/exercism/xrust/pull/217).

**Comment by IanWhitney** [comment]
Thank you. I hope to review that tomorrow. Sorry for the delay.

**Comment by IanWhitney** [comment]
> I have completed most of the work, but I noticed that only the first test in other crates are run, and the subsequent ones are ignored. Why so? 

When we're working on implementing a problem, we run all the test. But when we commit the final version we mark all-but-the-first test as `#[ignore]`. All of the Exercism tracks do this, so that students only have to worry about passing one test at a time.

> Also; I am unable to figure out how to run the tests from the tests folder. I used the cargo test command, but it shows an error saying that it can't find the crate..

While working on it, you need to put a copy of your `example.rs` code in `src/lib.rs`. When you run `cargo test` it tries to compile the file in `src/lib.rs`. The error you're seeing is because that file is not there.
