### ISSUE TITLE
space-age tests aren't checking results properly

### ISSUE THREAD

**Issue by zenspider** [exercism/xrust#188]
This passes and has NO reason to: 

http://exercism.io/submissions/2d8927ee710c403c8c822d9bfba4f565

**Comment by zenspider** [comment]
Found it. Thanks durka42 on moz's IRC:

```
    let diff: f64 = expected - actual.abs();
```

should be:

```
    let diff: f64 = (expected - actual).abs();
```

**Comment by petertseng** [comment]
Whoops =D. Thanks for reporting!
