### ISSUE TITLE
[question] why `extern crate hamming as dna;`

### ISSUE THREAD

**Issue by ashleygwilliams** [exercism/xrust#194]
i am interested in the reasoning behind the line `extern crate hamming as dna;`.

**Comment by IanWhitney** [comment]
It was called `point_mutations` and the original implementer aliased the crate name as `dna`, probably just for brevity

https://github.com/exercism/xrust/commit/6895c352c5f8deb2c503410546f9db94fb2e54ec

Exercism then changed the name of this exercise to `hamming` and when I updated the tests I just did a find & replace.

In short, no real good reason.

**Comment by petertseng** [comment]
In addition to what's said, it seems that we may not want to talk about DNA in Hamming exercise https://github.com/exercism/x-common/issues/323

So, it is probably appropriate to remove the `as dna`

**Comment by Henning-K** [comment]
I'd like to take this up as it seems like a relatively easy fix and good exercise for my first pull request.

**Comment by petertseng** [comment]
Nicely done!

**Comment by ashleygwilliams** [comment]
cool! :tada:
