### ISSUE TITLE
final test in word counts exercise does not seem like a good idea

### ISSUE THREAD

**Issue by ashleygwilliams** [exercism/xrust#196]
is there a class of symbols that this test is referring to? this doesn't seem like a good test. it requires that the student hardcode splitting on spaces AND underscores AND commas... and potentially Some Other Undefined "symbols". is there a reason you think this test is useful? this adds a lot of complexity that seems not terrible useful. i.e. this breaks if the sentence is "my twitter handle is @ag_dubs"

```rust
#[test]
#[ignore]
fn test_symbols_are_separators() {
    check_word_count(
        "hey,my_spacebar_is_broken.",
        vec![("hey", 1),
             ("my", 1),
             ("spacebar", 1),
             ("is", 1),
             ("broken", 1)]);
}
```

**Comment by IanWhitney** [comment]
This test isn't part of the [current canonical test suite](https://github.com/exercism/x-common/blob/538376ea0358a09ca4e4de71fa5b0e93abf2d184/word-count.json), and the [oldest commit I see for this file](https://github.com/exercism/xrust/blob/04b665e989b578c4e46ff100b1b0a00d5df9bb0d/exercises/word-count/tests/word-count.rs) doesn't explain the origin of the test.

A PR that updates the word-count test suite to the current canonical set would be a good fix for this issue.

**Comment by cyborgsphinx** [comment]
Looking at the rest of the tests, it might be that the intention was to define a word as a group of letters and numbers surrounded by characters which are neither. And according to that, 'ag_dubs' should be two words.

Though it is a moot point since it's been removed from the canonical test suite.

**Comment by petertseng** [comment]
The test was added in https://github.com/exercism/exercism.io/pull/650.
