### ISSUE TITLE
variable-length-quantity: wrong test case

### ISSUE THREAD

**Issue by shybyte** [exercism/xrust#224]
The readme says:   

>  The largest integer allowed is 0FFFFFFF, which translates to 4 bytes variable length. 

which contradicts this test case "from_bytes":

```
assert_eq!(&[0xffff_ffff],
           vlq::from_bytes(&[0x8f, 0xff, 0xff, 0xff, 0x7f]).unwrap().as_slice());
```

**Comment by petertseng** [comment]
I wonder why that is the largest allowed integer. https://en.wikipedia.org/wiki/Variable-length_quantity says:

> A variable-length quantity (VLQ) is a universal code that uses an arbitrary number of binary octets (eight-bit bytes) to represent an arbitrarily large integer.

Given this, should it be that the README removes that sentence about the largest integer?

**Comment by petertseng** [comment]
I believe our tests are correct and the README is wrong.
