### ISSUE TITLE
Investigate track health and status of the track

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xrust#226]
I've used Sarah Sharp's [FOSS Heartbeat](https://github.com/sarahsharp/foss-heartbeat) project to generate stats for each of the language track repositories, as well as the x-common repository.

The Exercism heartbeat data is published here: https://exercism.github.io/heartbeat/

When looking at the data, please disregard any activity from me (`kytrinyx`), as I would like to get the language tracks to a point where they are entirely maintained by the community.

Please take a look at the heartbeat data for this track, and answer the following questions:

* To what degree is the track maintained?
* Who (if anyone) is merging pull requests?
* Who (if anyone) is reviewing pull requests?
* Is there someone who is not merging pull requests, but who comments on issues and pull requests, has thoughtful feedback, and is generally helpful? If so, maybe we can invite them to be a maintainer on the track.

I've made up the following scale:

* **ORPHANED** - Nobody (other than me) has merged anything in the past year.
* **ENDANGERED** - Somewhere between ORPHANED and AT RISK.
* **AT RISK** - Two people (other than me) are actively discussing issues and reviewing and merging pull requests.
* **MAINTAINED** - Three or more people (other than me) are actively discussing issues and reviewing and merging pull requests.

It would also be useful to know if there a lot of activity on the track, or just the occasional issue or comment.

Please report the current status of the track, including your best guess on the above scale, back to the top-level issue in the discussions repository: https://github.com/exercism/discussions/issues/97

**Comment by petertseng** [comment]
What's changed in our status in the past year+?

As a reminder, in November 2016: https://github.com/exercism/discussions/issues/97#issuecomment-261821911:

> * Two maintainers
> * We get some issues & sometimes get a PR from other Rust track students.
> * @ijanos has contributed a few exercises, so he might be a good candidate for adding to the team

We added @ijanos and @coriolinus in the past year 🎉 

I can't speak for everyone else but for me personally I can't currently give this track a lot of priority. I can review others' changes but can't initiate many changes myself.

Though there was a period of a few weeks where we were letting PRs sit for a few weeks, I think nowadays we do OK at responding to others' PRs in a timely manner?

**Comment by kytrinyx** [comment]
> We added @ijanos and @coriolinus in the past year

This is fantastic. 🌷 🌷 🌷
