### ISSUE TITLE
Triangle: equilateral triangles are isosceles

### ISSUE THREAD

**Issue by clemensw** [exercism/xrust#228]
I agree the coding is more interesting, but I have a hard time accepting
    assert!(triangle.is_equilateral());
    assert!(!triangle.is_isosceles());

**Comment by petertseng** [comment]
Given that https://github.com/exercism/x-common/issues/379 has been discussed and https://github.com/exercism/x-common/pull/424 has been merged as a result, we should comply with the suite.

Re-visiting https://github.com/exercism/xrust/pull/206 would be a quick win in this area, though it may be worth it to rewrite the test suite follow the structure of the new JSON file.

**Comment by IanWhitney** [comment]
Agreeing with @petertseng here. I think if you have an approach that you want to suggest, updating the official JSON file is the way to go.
