### ISSUE TITLE
Add helpful information to the SETUP.md

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xrust#23]
The contents of the SETUP.md file gets included in
the README.md that gets delivered when a user runs the `exercism fetch`
command from their terminal.

At the very minimum, it should contain a link to the relevant
language-specific documentation on
[help.exercism.io](http://help.exercism.io).

It would also be useful to explain in a generic way how to run the tests.
Remember that this file will be included with _all_ the problems, so it gets
confusing if we refer to specific problems or files.

Some languages have very particular needs in terms of the solution: nested
directories, specific files, etc. If this is the case here, then it would be
useful to explain what is expected.

------

Thanks, @tejasbubane for suggesting that we add this documentation everywhere.
See [exercism.io#2198](https://github.com/exercism/exercism.io/issues/2198).

**Comment by pminten** [comment]
This is hard to do at the moment since we're not sure yet how the tests will run in the future (i.e. whether cargo will be involved or not).

**Comment by bitborn** [comment]
I just submitted another PR (#26) to get all the examples working with Cargo. 
If everybody likes the way that works out, I could write the setup file and some README's which would:

1. Point to the [Rust install page](http://www.rust-lang.org/install.html) (all versions should come with cargo)
2. Telling the user that once they create a file they can `cd` into a exercise directory and run `cargo test` to compile and run all the tests.

The question is _should we follow the Nightly or Beta channel?_

**Comment by kytrinyx** [comment]
Yeah, it's better to hold off until that has been resolved.

**Comment by EduardoBautista** [comment]
@bitborn We would only have to recommend Nightly or Beta until May 15th, which is when 1.0.0 is planned to ship.

**Comment by EduardoBautista** [comment]
I don't really understand where exactly the SETUP.md file is included.

**Comment by kytrinyx** [comment]
When the README for each exercise is assembled, it takes:

- The name of the exercise (based on the directory name for the problem)
- The shared description from $PROBLEM.md from x-common https://github.com/exercism/x-common)
- The contents of SETUP.md
- The source information from $PROBLEM.yml

**Comment by EduardoBautista** [comment]
In that order I assume?

**Comment by EduardoBautista** [comment]
Here it is: https://github.com/exercism/xrust/pull/28

**Comment by pminten** [comment]
Yup, looks great.
