### ISSUE TITLE
Gigasecond - Official Time Crate

### ISSUE THREAD

**Issue by Krakn** [exercism/xrust#230]
https://doc.rust-lang.org/time/time/index.html

Rust now has an official library for handling time. Would it be worth our time to replace [chrono](https://crates.io/crates/chrono) with [time](https://crates.io/crates/time)?

**Comment by ijanos** [comment]
Nothing changed, time crate is still deprecated.

**Comment by Krakn** [comment]
> Notes
> 
> This library is no longer actively maintained, but bugfixes will be added (details).
> 
> In case you're looking for something a little fresher and more actively maintained have a look at the chrono crate.

I guess I should have done some more digging last night.

@ijanos @petertseng - Thanks for your time!
