### ISSUE TITLE
Hello World as first exercise - is it OK to introduce Option so early?

### ISSUE THREAD

**Issue by petertseng** [exercism/xrust#251]
Hello World is our first exercise. It introduces Options.

https://github.com/exercism/x-common/issues/290#issuecomment-237998505

Ian said it best:

> Some/None. Really? We did that in Hello World?

Is it too much of a hurdle for students to get over, or are students usually good enough at looking up https://doc.rust-lang.org/std/option/ that they can figure it out?

If anyone has evidence to share one way or the other, I'd be pleased if you could help by sharing it. I'd also like to know because the Haskell track also wants to add hello-world (https://github.com/exercism/xhaskell/pull/475)

**Comment by petertseng** [comment]
Question you might ask: "If we for some reason decided to remove hello world, when would Option be introduced again?"

I believe the answer is when we use Result in hamming. Not exactly Option, but close enough.

**Comment by ErikSchierboom** [comment]
Speaking for myself, I think I'd be rather confused if `hello-world` would be the first exercise. Options are not that difficult, but `leap` for example is easier I believe. But then again, I'm perhaps not the average Haskell programmer.

**Comment by petertseng** [comment]
> If anyone has evidence 

Well, uh, I have stats? Here are some languages that either do or could ostensibly use option/maybe/whatever analogous concept in their hello world tests:

Do not have hello world:

* http://exercism.io/stats/haskell (would use Maybe)

Have hello world:

* http://exercism.io/stats/elm (uses Maybe)
* http://exercism.io/stats/kotlin (NB: uses *both* non-nullables and optional argument)
* http://exercism.io/stats/ocaml (uses option)
* http://exercism.io/stats/rust (uses Option)

For the following tracks, including their stats in the comparison would not be a direct comparison against the above languages because:

* crystal (types are non-nullable, but they use optional arguments in their hello-world)
* scala (has Option, but all reference types are still nullable, and uses optional arguments in hello-world)
* swift (types are non-nullable, but they use optional arguments in their hello-world)

You know what? I honestly don't know if there are interesting insights to be gained from these stats, but I'll post them here anyway in case anyone does see anything interesting!

**Comment by ErikSchierboom** [comment]
The F# track also uses optional values.

**Comment by petertseng** [comment]
Embarrassing that I forgot it. Added to list.

**Comment by petertseng** [comment]
Also lol at me using both "option" (the algebraic data type of `Some t | None` or `Just a | Nothing`) and "optional argument" (the ability to call a function passing a different number of arguments). I'm editing my comment to say "default argument" instead of "optional argument" to make it less confusing.

**Comment by petertseng** [comment]
I also didn't realize so many languages were doing this. Maybe I should have asked in a more general place, rather than the Rust track. I only knew that Rust was using option, and didn't do my research to see that other tracks were as well.

**Comment by petertseng** [comment]
We can talk about this in https://github.com/exercism/x-common/pull/520

by the way I missed purescript - they also use option.
