### ISSUE TITLE
Test case: you_can_validate_from_a_u32 for luhn-from and luhn-trait is not correct.

### ISSUE THREAD

**Issue by harishjp** [exercism/xrust#263]
Here is the result of manual computation. I noticed that it is derived from "046 454 286" But the trouble is the leading 0 is ignored for the integer and hence the luhn value is different.

Test: 46_454_286
Expression: 4 + (6 * 2 - 9) + 4 + (5 * 2 - 9) + 4 + (2 * 2) + 8 + (6 * 2 - 9) = 31

**Comment by petertseng** [comment]
leading zeroes shouldn't matter though.

In "046 454 286", you double every second digit from the right: that's the 8, 4, 4, and 4.

In "46 454 286", you double every second digit from the right: that's the 8, 4, 4, and 4.

The same digits are doubled, so the leading 0 makes no difference.

**Comment by petertseng** [comment]
> so the leading 0 makes no difference.

So any number of leading zeroes makes no difference, since they're all added at the left end, not the right end.

**Comment by petertseng** [comment]
Thus, I believe the tests currently in the track are correct as-is. Let us know if the above comment forgot to take something into consideration.

**Comment by harishjp** [comment]
:-) Thanks. This is awesome, I did this from left to right all this time and the tests passed except this one. Do not know how I missed right to left.

**Comment by petertseng** [comment]
I think it's because all the tests had odd number of characters, so left-to-right vs right-to-left did not matter. If we had a test for "59", we would have caught that. The test was recently added in #253.
