### ISSUE TITLE
#[ignore] isn't sufficient to hide tests from compilation.

### ISSUE THREAD

**Issue by jcdyer** [exercism/xrust#275]
Tests marked with `#[ignore]` still have to type check in order to compile, so you more or less have to complete the exercise to get the first test to pass.  In order to better facilitate incremental development using TDD practices, I suggest we actually comment out the tests instead of annotating them.

**Comment by ijanos** [comment]
Thanks you for pointing that out. We have another discussion #269 about placeholder lib.rs files. If we provide those with the right signatures this one became a non-issue because the empty exercises will compile without an issue as all tests will compile. Would that be a good solution for you?

**Comment by jcdyer** [comment]
I'm okay with either approach, though I think I mildly prefer having users write functions from scratch, as learning how to appease the typechecker is a large part of learning rust.

**Comment by jcdyer** [comment]
Closing this as a duplicate of #269
