### ISSUE TITLE
Need ABOUT.md

### ISSUE THREAD

**Issue by outkaj** [exercism/xrust#57]
We need a short, friendly introduction to Rust for the website as specified [here] (http://exercism.io/languages/rust). 

The description should at minimum reference Rust's focus on safety and the combination of low-level control with functional features such as pattern matching. 

An ABOUT.md file should be made and put into docs/.

**Comment by outkaj** [comment]
See e63b256.

**Comment by petertseng** [comment]
Got a first pass in #69 - more work to come in #88 as well.
