### ISSUE TITLE
Rust Exercise Proposal

### ISSUE THREAD

**Issue by mglodack** [exercism/xrust#73]
I've recently taken on the challenge of creating a rust query string builder, and I found it to be a rewarding exercise.

I've learned more about `Strings, Vectors, Tuples, the ownership system, as well as iterator traits like map and fold`, and I thought this would be a great exercise on exercism.

##### Exercise:

```
Write a program that provided a list of tuples can return a http query string.

For example:

Input: 
let params = vec![("key1", "value1"), ("key2", "value2")];

Output: 
"?key1=value1&key2=value2"
```

**Comment by EduardoBautista** [comment]
Hmmm, I can't recall of a way to create an exercise specific to a single track only.  Maybe this could be made to be more general.  A vector of tuples could easily be an array of arrays in many languages.

I'd recommend proposing this exercise in [x-common](https://github.com/exercism/x-common).

**Comment by kytrinyx** [comment]
Yes, please do propose the exercise in x-common, in a form that would allow other tracks to implement it if they wish to.

**Comment by petertseng** [comment]
Looks like we can safely move the discussion to https://github.com/exercism/x-common/issues/225 now
