### ISSUE TITLE
"point-mutations" is deprecated in favor of hamming

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xrust#74]
This happened a while back, and it was for really weird legacy reasons.

I've since fixed the underlying issues that caused the problem, but for consistency
it would be nice to rename point-mutation to hamming, so that all the tracks are using
the same exercise name.

Once the problem has been renamed, I can run a script on the website to point people's
existing point-mutations solutions to the new hamming exercise so that they'll be able
to review solutions to hamming, and people who solve the new hamming exercise can see
all the old ones.

**Comment by EduardoBautista** [comment]
If anyone wants to send a PR for this, all you have to do is rename the all the files, directories, and variables from `point-mutations` (there is a couple `point_mutations` as well) to `hamming`.  Also, be sure to update the `config.json`.  

If no one takes it in a couple of days, I will send a PR.
