### ISSUE TITLE
Remove the `as_ref` check in RNA?

### ISSUE THREAD

**Issue by IanWhitney** [exercism/xrust#76]
This might be because I'm new to Rust, but I don't see the value of [this test](https://github.com/exercism/xrust/blob/04b665e989b578c4e46ff100b1b0a00d5df9bb0d/exercises/rna-transcription/tests/rna-transcription.rs#L41) in the RNA transcription exercise. It doesn't seem germane to the problem, and [the commit that introduced it](https://github.com/exercism/xrust/commit/312c462a19c07c2bc3f4c7d28893339374bbb7fb) doesn't really explain why it's there.

Its presence seems to require the solver to implement `AsRef` for their Struct (as shown in [the example solution](https://github.com/exercism/xrust/commit/312c462a19c07c2bc3f4c7d28893339374bbb7fb)) just so that the test can be passed. Implementing AsRef doesn't add any other value, as far as I can see. All the other tests are passable without implementing AsRef.

But, again, new to Rust here so I'm probably missing something. My solution, which passes all tests but the `as_ref` one is here: https://gist.github.com/IanWhitney/b2ac83ae8195f5fc1a75

**Comment by kytrinyx** [comment]
I'm not sure (not familiar with Rust). @bitborn do you remember what this was about?
@petertseng @EduardoBautista do you have any ideas here?

**Comment by petertseng** [comment]
In [its initial form](https://github.com/exercism/xrust/commit/7877d6389ed47d8c3e6631274c1c66a0b4c4ec54), it appears this test just wanted conversion to a string. Asking for that may be clearer than `as_ref`. I would have suggested https://doc.rust-lang.org/std/string/trait.ToString.html, but apparently you shouldn't implement this directly but instead should implement https://doc.rust-lang.org/std/fmt/trait.Display.html which requires students to thin about Formatters. Might be a bit much.

Of course there's the question of "what's the value in asking students to be able to convert their RNA to a string anyway?". That I'd want to take some time to survey this problem in other languages to understand why. I've not thought about this exercise before.

**Comment by IanWhitney** [comment]
FWIW, I'm familiar with the Elixir and Ruby version of this exercise and they don't have any tests like this.

**Comment by petertseng** [comment]
I'm not by any means an expert on best practices in Rust (which is only relevant if there's some Rust practices reason for keeping this test in), but my current thinking is to agree - the test on converting to a string is not really useful (it's not to do with the problem statement, there's no clear use case for converting the RNA to a string). I'm in favor of removing it.
