### ISSUE TITLE
Domino test case clarification of chain

### ISSUE THREAD

**Issue by masters3d** [exercism/xrust#82]
What does Correct Chain mean in domino?

Couldn't the below test case output ?
41 12 23
not valid?

```rust
fn invalid_input() {
    let input = vec!((1, 2), (4, 1), (2, 3));
    assert_eq!(dominoes::chain(&input), None);
}
```

**Comment by petertseng** [comment]
you cannot make a chain out of this set of dominoes, therefore `dominoes::chain(vec![(1, 2), (4, 1), (2, 3)])` returns `None` instead of `Some(chain)` where `chain` is the valid chain

**Comment by masters3d** [comment]
This was a challenging exercise! 
Thanks!

**Comment by asarkar** [comment]
I don't understand why the following aren't valid, i.e. the corresponding tests expect `None`:
Input: [(1, 1), (2, 2)], Output: [(1, 2), (2, 1)]
Input: [(1, 2), (2, 1), (3, 4), (4, 3)], Output: [(3, 4), (4, 2), (2, 1), (1, 3)]

**Comment by coriolinus** [comment]
A domino has two numbers physically etched onto the same stone. This image would correspond to `(3, 4)`:

![](https://freesvg.org/img/molumen_domino_set_19.png)

Individual domino stones are immutable; the same pair of numbers is always present on each stone, though you can of course place the stone in either orientation.

Your proposed solution is not possible with physical domino stones and is disallowed in the test cases.

**Comment by asarkar** [comment]
Got it! In other words, the dominoes in the output `[(1, 2), (2, 1)]` aren't present in the input. Thanks.
