### ISSUE TITLE
Revisiting Roman Numerals API

### ISSUE THREAD

**Issue by JIghtuse** [exercism/xrust#99]
So, @IanWhitney [agreed](http://exercism.io/submissions/3d5665d6626747989e3cf9328e73f761) that API used for Roman Numerals is unfortunate. [Test suite](http://exercism.io/exercises/rust/roman-numerals) has this:

    assert_eq!("I", Roman::from(1));

Which looks like [`trait From`](https://doc.rust-lang.org/std/convert/trait.From.html).This trait is supposed to convert some type to the type `From` implemented for (`i32` to `Roman` in this case). Instead, the result of `from` is used like `&str` or `String`. It is still possible to use `trait From` if we combine it with, say, [`PartialEq`](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html). But then implementation looks verbose and unidiomatic.

The question is, how should a new API look like? Any suggestions?

Here is my proposal:

    let roman = Roman::new(4);
    assert_eq!("IV", roman.to_string());

Which hints to implement `Roman::new()` like many Rust structs do, and [`trait Display`](https://doc.rust-lang.org/std/fmt/trait.Display.html). Thoughts?

**Comment by IanWhitney** [comment]
Yeah, when I implemented that exercise I didn't quite understand the `From` trait, so I wasn't aware that I was using a word that has a specific meaning in Rust.

In terms of Rust idioms, I wonder if it's reasonable to coerce an integer into a Roman? The usual example of the From trait is 

```
let x = String::from("Hello");
```

Which coerces a &str into a String. 

I'm not sure how that's different from

```
let x = Roman::from(1);
```

Which coerces a Integer into a Roman.

**Comment by JIghtuse** [comment]
@IanWhiney hm, actually yes, I think using `Roman::from ()` is fine too, if we add some function to convert Roman to String. Otherwise it looks confusing.

**Comment by IanWhitney** [comment]
What if the API was `Roman::from(1).to_string`?

**Comment by JIghtuse** [comment]
@IanWhitney I think it would be nice. Are you going to implement it?

**Comment by IanWhitney** [comment]
I can. I might not have time to get to to it until next week. I'm also happy to merge PRs from others.

**Comment by petertseng** [comment]
Having both seems good; seems a useful opportunity to use the respective traits. Though it may not be that everyone will pick up on the traits. Can and should we check that students actually `impl` the traits? Or should that be left for reviewers to suggest?

Also someone may ask "So why do this `from` and `to` business", but I imagine the answer would be "this leaves the door open to conversions to/from other types as well".

Other than that I think I have nothing more to add; we seem to have reached agreement

**Comment by IanWhitney** [comment]
There may be a way to check trait implementation, but I don't think it's necessary. Seems like something that should be handled via nitpicking.
